# CMake generated Testfile for 
# Source directory: /mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/RunCMake
# Build directory: /mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/RunCMake
# 
# This file includes the relevent testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(RunCMake.Languages "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/bin/cmake" "-DCMAKE_MODULE_PATH=/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_SOURCE_DIR=/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/RunCMake/Languages" "-DRunCMake_BINARY_DIR=/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/RunCMake/Languages" "-P" "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/RunCMake/Languages/RunCMakeTest.cmake")
ADD_TEST(RunCMake.ObjectLibrary "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/bin/cmake" "-DCMAKE_MODULE_PATH=/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_SOURCE_DIR=/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/RunCMake/ObjectLibrary" "-DRunCMake_BINARY_DIR=/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/RunCMake/ObjectLibrary" "-P" "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/RunCMake/ObjectLibrary/RunCMakeTest.cmake")
ADD_TEST(RunCMake.build_command "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/bin/cmake" "-DCMAKE_MODULE_PATH=/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_SOURCE_DIR=/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/RunCMake/build_command" "-DRunCMake_BINARY_DIR=/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/RunCMake/build_command" "-P" "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/RunCMake/build_command/RunCMakeTest.cmake")
ADD_TEST(RunCMake.find_package "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/bin/cmake" "-DCMAKE_MODULE_PATH=/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_SOURCE_DIR=/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/RunCMake/find_package" "-DRunCMake_BINARY_DIR=/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/RunCMake/find_package" "-P" "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/RunCMake/find_package/RunCMakeTest.cmake")
ADD_TEST(RunCMake.include "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/bin/cmake" "-DCMAKE_MODULE_PATH=/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_SOURCE_DIR=/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/RunCMake/include" "-DRunCMake_BINARY_DIR=/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/RunCMake/include" "-P" "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/RunCMake/include/RunCMakeTest.cmake")
ADD_TEST(RunCMake.list "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/bin/cmake" "-DCMAKE_MODULE_PATH=/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_SOURCE_DIR=/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/RunCMake/list" "-DRunCMake_BINARY_DIR=/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/RunCMake/list" "-P" "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/RunCMake/list/RunCMakeTest.cmake")
