# CMake generated Testfile for 
# Source directory: /mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/CMakeTests
# Build directory: /mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/CMakeTests
# 
# This file includes the relevent testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(CMake.List "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/bin/cmake" "-P" "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/CMakeTests/ListTest.cmake")
ADD_TEST(CMake.VariableWatch "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/bin/cmake" "-P" "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/CMakeTests/VariableWatchTest.cmake")
ADD_TEST(CMake.Include "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/bin/cmake" "-P" "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/CMakeTests/IncludeTest.cmake")
ADD_TEST(CMake.FindBase "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/bin/cmake" "-P" "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/CMakeTests/FindBaseTest.cmake")
ADD_TEST(CMake.Toolchain "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/bin/cmake" "-P" "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/CMakeTests/ToolchainTest.cmake")
ADD_TEST(CMake.GetFilenameComponentRealpath "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/bin/cmake" "-P" "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/CMakeTests/GetFilenameComponentRealpathTest.cmake")
ADD_TEST(CMake.Version "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/bin/cmake" "-P" "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/CMakeTests/VersionTest.cmake")
ADD_TEST(CMake.Message "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/bin/cmake" "-P" "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/CMakeTests/MessageTest.cmake")
ADD_TEST(CMake.File "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/bin/cmake" "-P" "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/CMakeTests/FileTest.cmake")
ADD_TEST(CMake.ConfigureFile "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/bin/cmake" "-P" "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/CMakeTests/ConfigureFileTest.cmake")
ADD_TEST(CMake.SeparateArguments "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/bin/cmake" "-P" "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/CMakeTests/SeparateArgumentsTest.cmake")
ADD_TEST(CMake.ImplicitLinkInfo "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/bin/cmake" "-P" "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/CMakeTests/ImplicitLinkInfoTest.cmake")
ADD_TEST(CMake.ModuleNotices "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/bin/cmake" "-P" "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/CMakeTests/ModuleNoticesTest.cmake")
ADD_TEST(CMake.GetProperty "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/bin/cmake" "-P" "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/CMakeTests/GetPropertyTest.cmake")
ADD_TEST(CMake.If "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/bin/cmake" "-P" "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/CMakeTests/IfTest.cmake")
ADD_TEST(CMake.String "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/bin/cmake" "-P" "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/CMakeTests/StringTest.cmake")
ADD_TEST(CMake.Math "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/bin/cmake" "-P" "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/CMakeTests/MathTest.cmake")
ADD_TEST(CMake.CMakeMinimumRequired "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/bin/cmake" "-P" "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/CMakeTests/CMakeMinimumRequiredTest.cmake")
ADD_TEST(CMake.CompilerIdVendor "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/bin/cmake" "-P" "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/CMakeTests/CompilerIdVendorTest.cmake")
ADD_TEST(CMake.ProcessorCount "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/bin/cmake" "-P" "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/CMakeTests/ProcessorCountTest.cmake")
ADD_TEST(CMake.PushCheckState "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/bin/cmake" "-P" "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/CMakeTests/PushCheckStateTest.cmake")
ADD_TEST(CMake.While "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/bin/cmake" "-P" "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/CMakeTests/WhileTest.cmake")
ADD_TEST(CMake.FileDownload "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/bin/cmake" "-P" "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/CMakeTests/FileDownloadTest.cmake")
SET_TESTS_PROPERTIES(CMake.FileDownload PROPERTIES  PASS_REGULAR_EXPRESSION "file already exists with expected MD5 sum")
ADD_TEST(CMake.FileUpload "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/bin/cmake" "-P" "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/CMakeTests/FileUploadTest.cmake")
ADD_TEST(CMake.ELF "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/bin/cmake" "-P" "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/CMakeTests/ELFTest.cmake")
ADD_TEST(CMake.EndStuff "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/bin/cmake" "-Ddir:STRING=/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/CMakeTests/EndStuffTest" "-P" "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/CMakeTests/EndStuffTest.cmake")
ADD_TEST(CMake.GetPrerequisites "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/bin/cmake" "-DCTEST_CONFIGURATION_TYPE:STRING=${CTEST_CONFIGURATION_TYPE}" "-P" "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/CMakeTests/GetPrerequisitesTest.cmake")
ADD_TEST(CMake.CheckSourceTree "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/bin/cmake" "-DCMake_BINARY_DIR:PATH=/mnt/oqtansTools/oqtans_src/cmake-2.8.9" "-DCMake_SOURCE_DIR:PATH=/mnt/oqtansTools/oqtans_src/cmake-2.8.9" "-DGIT_EXECUTABLE:STRING=/usr/bin/git" "-DHOME:STRING=/home/ubuntu" "-P" "/mnt/oqtansTools/oqtans_src/cmake-2.8.9/Tests/CMakeTests/CheckSourceTreeTest.cmake")
